/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DietasRouteImport } from './routes/dietas'
import { Route as MedicamentosRouteImport } from './routes/medicamentos'
import { Route as NutricaoEsportivaRouteImport } from './routes/nutricao-esportiva'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as ProtocolosRouteImport } from './routes/protocolos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DietasRoute = DietasRouteImport.update({
  id: '/dietas',
  path: '/dietas',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentosRoute = MedicamentosRouteImport.update({
  id: '/medicamentos',
  path: '/medicamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoEsportivaRoute = NutricaoEsportivaRouteImport.update({
  id: '/nutricao-esportiva',
  path: '/nutricao-esportiva',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosRoute = ProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dietas': typeof DietasRoute
  '/medicamentos': typeof MedicamentosRoute
  '/nutricao-esportiva': typeof NutricaoEsportivaRoute
  '/pacientes': typeof PacientesRoute
  '/protocolos': typeof ProtocolosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dietas': typeof DietasRoute
  '/medicamentos': typeof MedicamentosRoute
  '/nutricao-esportiva': typeof NutricaoEsportivaRoute
  '/pacientes': typeof PacientesRoute
  '/protocolos': typeof ProtocolosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dietas': typeof DietasRoute
  '/medicamentos': typeof MedicamentosRoute
  '/nutricao-esportiva': typeof NutricaoEsportivaRoute
  '/pacientes': typeof PacientesRoute
  '/protocolos': typeof ProtocolosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dietas'
    | '/medicamentos'
    | '/nutricao-esportiva'
    | '/pacientes'
    | '/protocolos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dietas'
    | '/medicamentos'
    | '/nutricao-esportiva'
    | '/pacientes'
    | '/protocolos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dietas'
    | '/medicamentos'
    | '/nutricao-esportiva'
    | '/pacientes'
    | '/protocolos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DietasRoute: typeof DietasRoute
  MedicamentosRoute: typeof MedicamentosRoute
  NutricaoEsportivaRoute: typeof NutricaoEsportivaRoute
  PacientesRoute: typeof PacientesRoute
  ProtocolosRoute: typeof ProtocolosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dietas': {
      id: '/dietas'
      path: '/dietas'
      fullPath: '/dietas'
      preLoaderRoute: typeof DietasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamentos': {
      id: '/medicamentos'
      path: '/medicamentos'
      fullPath: '/medicamentos'
      preLoaderRoute: typeof MedicamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao-esportiva': {
      id: '/nutricao-esportiva'
      path: '/nutricao-esportiva'
      fullPath: '/nutricao-esportiva'
      preLoaderRoute: typeof NutricaoEsportivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos': {
      id: '/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof ProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DietasRoute: DietasRoute,
  MedicamentosRoute: MedicamentosRoute,
  NutricaoEsportivaRoute: NutricaoEsportivaRoute,
  PacientesRoute: PacientesRoute,
  ProtocolosRoute: ProtocolosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
