alter table public.diet_plans
  add column if not exists beverages jsonb not null default '[]'::jsonb
  check (jsonb_typeof(beverages) = 'array');

update public.diet_plans set beverages = case condition_key
  when 'gastrite' then '[{"type":"Priorize","name":"Água sem gás","note":"Bebida base; não há bebida que cure gastrite ou elimine H. pylori."},{"type":"Observe","name":"Café, chá cafeinado, refrigerantes e sucos ácidos","note":"Podem piorar sintomas em algumas pessoas; teste individualmente, sem proibição automática."},{"type":"Atenção","name":"Álcool","note":"Pode irritar o estômago e causar gastropatia erosiva; converse com o médico, especialmente durante tratamento medicamentoso."}]'::jsonb
  when 'gastrite-autoimune' then '[{"type":"Priorize","name":"Água sem gás","note":"Opção simples para hidratação; não corrige má absorção de ferro ou vitamina B12."},{"type":"Observe","name":"Café, bebidas gaseificadas ou sucos ácidos","note":"Reduza apenas se notar piora dos sintomas."},{"type":"Atenção","name":"Álcool","note":"Pode irritar ou lesar a mucosa; discuta consumo com a equipe de saúde."}]'::jsonb
  when 'gastropatia-erosiva' then '[{"type":"Priorize","name":"Água sem gás","note":"Opção simples; siga restrições de líquidos se algum profissional já as prescreveu."},{"type":"Evite","name":"Bebidas alcoólicas","note":"O álcool pode causar ou agravar gastropatia erosiva."},{"type":"Observe","name":"Café, bebidas gaseificadas e sucos ácidos","note":"Ajuste caso provoquem sintomas; dieta não substitui tratar a causa."}]'::jsonb
  when 'dispepsia' then '[{"type":"Priorize","name":"Água sem gás","note":"Escolha simples para acompanhar as refeições e ao longo do dia."},{"type":"Observe","name":"Café, bebidas com cafeína ou gás e sucos","note":"Podem desencadear sintomas em algumas pessoas; anote a resposta individual."},{"type":"Atenção","name":"Álcool","note":"Pode irritar o trato digestivo; converse com a equipe se os sintomas persistirem."}]'::jsonb
  when 'refluxo' then '[{"type":"Priorize","name":"Água sem gás","note":"Opção simples; ajuste a quantidade conforme sua rotina e orientação profissional."},{"type":"Observe","name":"Café/chá cafeinado, álcool, bebidas cítricas e refrigerantes","note":"Podem piorar o refluxo em algumas pessoas; reduza apenas os gatilhos que você confirmar."},{"type":"Observe","name":"Bebidas com menta/hortelã ou chocolate","note":"Observe sintomas e converse com seu profissional; não é necessário excluir se não forem gatilhos."}]'::jsonb
  when 'sii-fodmap' then '[{"type":"Priorize","name":"Água sem gás","note":"Escolha base para a hidratação; não requer adoçantes nem ingredientes com FODMAPs."},{"type":"Observe","name":"Sucos de maçã/pera, refrigerantes e bebidas com xarope de milho rico em frutose","note":"Podem concentrar FODMAPs ou aumentar gases; confira ingredientes e porções no guia Monash."},{"type":"Observe","name":"Bebidas com sorbitol, manitol, xilitol ou outros poliálcoois","note":"Leia rótulos; esses adoçantes podem ser ricos em FODMAPs."},{"type":"Observe","name":"Café, álcool e bebidas gaseificadas","note":"Podem provocar sintomas por motivos além dos FODMAPs; reduza só se forem gatilhos pessoais."}]'::jsonb
  when 'lactose' then '[{"type":"Priorize","name":"Água","note":"Bebida sem lactose para acompanhar o dia."},{"type":"Priorize","name":"Leite sem lactose ou bebida de soja fortificada com cálcio e vitamina D","note":"Confira o rótulo e a tolerância individual; bebida vegetal não é automaticamente equivalente em nutrientes."},{"type":"Observe","name":"Leite comum, vitaminas, milk-shakes e bebidas com leite","note":"Contêm lactose em quantidades variáveis; algumas pessoas toleram porções menores, outras preferem versões sem lactose."}]'::jsonb
  when 'celiaca' then '[{"type":"Priorize","name":"Água, café e chá simples","note":"Confira que não haja malte, mistura com glúten ou contaminação no preparo."},{"type":"Priorize","name":"Bebidas industrializadas identificadas sem glúten","note":"Confira rótulos e possíveis ingredientes de trigo, cevada, centeio ou malte."},{"type":"Evite","name":"Cerveja e bebidas de malte/cevada","note":"Podem conter glúten; na doença celíaca confirmada, confira sempre rótulos e preparo."}]'::jsonb
  else beverages
end
where condition_key in ('gastrite', 'gastrite-autoimune', 'gastropatia-erosiva', 'dispepsia', 'refluxo', 'sii-fodmap', 'lactose', 'celiaca');

update public.diet_plans set sources = sources || case condition_key
  when 'gastrite' then '[{"label":"NIDDK — causas de gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/symptoms-causes"}]'::jsonb
  when 'gastrite-autoimune' then '[{"label":"NIDDK — causas de gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/symptoms-causes"}]'::jsonb
  when 'gastropatia-erosiva' then '[{"label":"NIDDK — causas de gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/symptoms-causes"}]'::jsonb
  when 'dispepsia' then '[{"label":"NIDDK — alimentação para dispepsia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/indigestion-dyspepsia/eating-diet-nutrition"}]'::jsonb
  when 'refluxo' then '[{"label":"NIDDK — bebidas e alimentação no refluxo","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition"}]'::jsonb
  when 'sii-fodmap' then '[{"label":"NIDDK — alimentação para gases e bebidas","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gas-digestive-tract/eating-diet-nutrition"},{"label":"Monash — dieta FODMAP","url":"https://monashfodmap.com/about-fodmap-and-ibs/high-and-low-fodmap-foods/"}]'::jsonb
  when 'lactose' then '[{"label":"NIDDK — bebidas sem lactose e nutrição","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/lactose-intolerance/eating-diet-nutrition"}]'::jsonb
  when 'celiaca' then '[{"label":"NIDDK — bebidas e alimentos com glúten","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/eating-diet-nutrition"}]'::jsonb
  else '[]'::jsonb
end
where condition_key in ('gastrite', 'gastrite-autoimune', 'gastropatia-erosiva', 'dispepsia', 'refluxo', 'sii-fodmap', 'lactose', 'celiaca');
