alter table public.diet_plans
  add column if not exists condition_key text not null default 'geral',
  add column if not exists variant smallint not null default 1 check (variant in (1, 2, 3)),
  add column if not exists variant_label text not null default 'Cardápio A';

update public.diet_plans set condition_key = case id
  when 'plano-gastrite' then 'gastrite'
  when 'plano-gastrite-autoimune' then 'gastrite-autoimune'
  when 'plano-gastropatia-erosiva' then 'gastropatia-erosiva'
  when 'plano-dispepsia' then 'dispepsia'
  when 'plano-refluxo' then 'refluxo'
  when 'plano-sii-fodmap' then 'sii-fodmap'
  when 'plano-lactose' then 'lactose'
  when 'plano-celiaca' then 'celiaca'
  else condition_key
end
where id like 'plano-%';

update public.diet_plans set variant = 1, variant_label = 'Cardápio A'
where id like 'plano-%';

create unique index if not exists diet_plans_active_condition_variant_idx
  on public.diet_plans (condition_key, variant) where is_active = true;

insert into public.diet_plans (id, name, goal, category, summary, caution, sources, kcal, water, meals, condition_key, variant, variant_label, is_active)
values
('plano-gastrite-b', 'Gastrite: refeições de exemplo', 'Sintomas variam; escolha o que tolera', 'Estômago', 'Combinação alternativa de alimentos simples. Não existe cardápio que cure gastrite; use apenas itens que você tolere.', 'Evite álcool, sobretudo com gastropatia erosiva. Alimentação não elimina H. pylori; procure avaliação para investigar e tratar a causa.', '[{"label":"NIDDK — dieta na gastrite","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Cuscuz de milho com ovo mexido e banana madura."},{"time":"10:00","name":"Lanche","items":"Melão ou mamão, se tolerados."},{"time":"12:30","name":"Almoço","items":"Arroz, peixe assado, chuchu e cenoura cozidos."},{"time":"16:00","name":"Lanche","items":"Tapioca recheada com frango desfiado."},{"time":"19:00","name":"Jantar","items":"Mandioquinha amassada com frango e abobrinha cozida."}]'::jsonb, 'gastrite', 2, 'Cardápio B', true),
('plano-gastrite-c', 'Gastrite: refeições de exemplo', 'Sintomas variam; escolha o que tolera', 'Estômago', 'Terceira combinação simples. Teste tolerância individual e varie sem excluir alimentos que não lhe causam sintomas.', 'Dieta não trata a causa da gastrite. Não suspenda medicamentos prescritos nem use suplementos por conta própria.', '[{"label":"NIDDK — dieta na gastrite","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Pão ou tapioca com ovo e mamão, conforme tolerância."},{"time":"10:00","name":"Lanche","items":"Banana ou melão."},{"time":"12:30","name":"Almoço","items":"Arroz, carne magra cozida e abóbora com vagem cozidas."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose, se tolerado, ou uma fruta."},{"time":"19:00","name":"Jantar","items":"Purê de batata, peixe assado e cenoura cozida."}]'::jsonb, 'gastrite', 3, 'Cardápio C', true),
('plano-gastrite-autoimune-b', 'Gastrite autoimune: refeições equilibradas', 'Nutrição e acompanhamento de ferro/B12', 'Estômago', 'Combinação variada com ovos, peixe e carne. Alimentos nutritivos ajudam a compor a dieta, mas podem não corrigir má absorção de ferro ou B12.', 'Converse com a equipe sobre exames de ferro e vitamina B12. A necessidade de suplemento ou injeção é decidida clinicamente.', '[{"label":"NIDDK — dieta na gastrite","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Omelete simples com tapioca e mamão."},{"time":"10:00","name":"Lanche","items":"Banana e castanhas, se toleradas."},{"time":"12:30","name":"Almoço","items":"Arroz, carne magra, feijão se tolerado e folhas/legumes cozidos."},{"time":"16:00","name":"Lanche","items":"Bebida de soja fortificada com cálcio, se tolerada, e fruta."},{"time":"19:00","name":"Jantar","items":"Batata assada, peixe e espinafre cozido."}]'::jsonb, 'gastrite-autoimune', 2, 'Cardápio B', true),
('plano-gastrite-autoimune-c', 'Gastrite autoimune: refeições equilibradas', 'Nutrição e acompanhamento de ferro/B12', 'Estômago', 'Outra seleção de refeições. Não substitui monitoramento laboratorial de deficiências nutricionais.', 'A gastrite autoimune pode reduzir absorção de nutrientes; cardápio sozinho não trata a causa nem substitui reposição prescrita.', '[{"label":"NIDDK — dieta na gastrite","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Cuscuz de milho com ovo e uma fruta tolerada."},{"time":"10:00","name":"Lanche","items":"Mamão ou banana."},{"time":"12:30","name":"Almoço","items":"Arroz, sardinha ou carne magra e abobrinha cozida."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose se tolerado ou pão/tapioca com ovo."},{"time":"19:00","name":"Jantar","items":"Mandioca cozida, frango e couve refogada/cozida, se tolerada."}]'::jsonb, 'gastrite-autoimune', 3, 'Cardápio C', true),
('plano-gastropatia-erosiva-b', 'Gastropatia reativa/erosiva: refeições de exemplo', 'Evitar álcool e avaliar a causa', 'Estômago', 'Combinação de refeições sem álcool. O cardápio não cicatriza erosões nem substitui avaliação da causa.', 'Evite álcool e converse com o médico sobre anti-inflamatórios e outros medicamentos; não os interrompa sem orientação.', '[{"label":"NIDDK — dieta na gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Tapioca com frango desfiado e banana."},{"time":"10:00","name":"Lanche","items":"Mamão ou pera, se tolerada."},{"time":"12:30","name":"Almoço","items":"Arroz, peixe cozido/assado e abóbora."},{"time":"16:00","name":"Lanche","items":"Ovo cozido e bolacha de arroz simples."},{"time":"19:00","name":"Jantar","items":"Canja caseira de arroz, frango, cenoura e chuchu."}]'::jsonb, 'gastropatia-erosiva', 2, 'Cardápio B', true),
('plano-gastropatia-erosiva-c', 'Gastropatia reativa/erosiva: refeições de exemplo', 'Evitar álcool e avaliar a causa', 'Estômago', 'Mais uma combinação de alimentos simples, sujeita à tolerância individual.', 'Sangue no vômito, fezes negras, fraqueza ou dor intensa requerem atendimento urgente. Procure tratamento para a causa da gastropatia.', '[{"label":"NIDDK — dieta na gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Mingau de arroz e ovo mexido."},{"time":"10:00","name":"Lanche","items":"Melão ou banana madura."},{"time":"12:30","name":"Almoço","items":"Purê de batata, frango assado e cenoura cozida."},{"time":"16:00","name":"Lanche","items":"Tapioca simples com ovo."},{"time":"19:00","name":"Jantar","items":"Arroz, peixe assado e abobrinha cozida."}]'::jsonb, 'gastropatia-erosiva', 3, 'Cardápio C', true),
('plano-dispepsia-b', 'Dispepsia: refeições menores de exemplo', 'Porções menores e gatilhos pessoais', 'Estômago', 'Segunda combinação dividida em pequenas refeições. Alimentos-gatilho variam de pessoa para pessoa.', 'Use porções ajustadas ao seu apetite. Se algum alimento piorar os sintomas, substitua apenas esse item; procure avaliação se houver sinais de alerta.', '[{"label":"NIDDK — alimentação para dispepsia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/indigestion-dyspepsia/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Cuscuz pequeno com ovo, se tolerado."},{"time":"10:00","name":"Lanche","items":"Mamão em pequena porção."},{"time":"12:30","name":"Almoço","items":"Arroz, peixe e abóbora cozida; coma devagar."},{"time":"15:30","name":"Lanche","items":"Tapioca pequena com frango desfiado."},{"time":"18:30","name":"Jantar","items":"Batata cozida, ovo e cenoura; pare ao se sentir confortavelmente satisfeito."}]'::jsonb, 'dispepsia', 2, 'Cardápio B', true),
('plano-dispepsia-c', 'Dispepsia: refeições menores de exemplo', 'Porções menores e gatilhos pessoais', 'Estômago', 'Terceira combinação com alimentos comuns e refeições menores, a ajustar à tolerância.', 'Bebidas gaseificadas, café e refeições gordurosas podem piorar sintomas em algumas pessoas; não são proibições universais.', '[{"label":"NIDDK — alimentação para dispepsia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/indigestion-dyspepsia/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Pão simples ou tapioca com ovo, se tolerados."},{"time":"10:00","name":"Lanche","items":"Banana madura."},{"time":"12:30","name":"Almoço","items":"Mandioquinha, frango desfiado e chuchu cozido."},{"time":"15:30","name":"Lanche","items":"Iogurte sem lactose se tolerado ou uma fruta."},{"time":"18:30","name":"Jantar","items":"Arroz, peixe e abobrinha; escolha uma porção confortável."}]'::jsonb, 'dispepsia', 3, 'Cardápio C', true),
('plano-refluxo-b', 'Refluxo: refeições de exemplo', 'Jantar pelo menos 3 h antes de deitar', 'Estômago', 'Outra combinação diária com jantar cedo. Evite somente gatilhos que você reconhece.', 'Se os sintomas aparecem à noite, termine a refeição pelo menos 3 horas antes de se deitar. Ajuste o horário conforme sua rotina de sono.', '[{"label":"NIDDK — alimentação para refluxo","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Cuscuz de milho com ovo e banana."},{"time":"10:00","name":"Lanche","items":"Mamão ou melão."},{"time":"12:30","name":"Almoço","items":"Arroz, frango grelhado e cenoura/vagem cozidas."},{"time":"15:30","name":"Lanche","items":"Tapioca pequena com frango ou fruta tolerada."},{"time":"18:00","name":"Jantar","items":"Purê de mandioquinha, peixe e abobrinha. Mantenha 3 h até deitar."}]'::jsonb, 'refluxo', 2, 'Cardápio B', true),
('plano-refluxo-c', 'Refluxo: refeições de exemplo', 'Jantar pelo menos 3 h antes de deitar', 'Estômago', 'Terceira combinação. Café, chocolate, hortelã, álcool, gordura e alimentos ácidos só precisam ser reduzidos se forem seus gatilhos.', 'Dor no peito, dificuldade para engolir, vômitos persistentes, sangue ou perda de peso precisam de avaliação clínica.', '[{"label":"NIDDK — alimentação para refluxo","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Aveia com bebida de soja fortificada se tolerada e banana."},{"time":"10:00","name":"Lanche","items":"Melão ou mamão."},{"time":"12:30","name":"Almoço","items":"Arroz, peixe assado e legumes cozidos."},{"time":"15:30","name":"Lanche","items":"Bolacha simples ou fruta que não provoque sintomas."},{"time":"18:00","name":"Jantar","items":"Batata cozida, frango e chuchu; ajuste para terminar 3 h antes de deitar."}]'::jsonb, 'refluxo', 3, 'Cardápio C', true),
('plano-sii-fodmap-b', 'Intestino irritável: exemplo baixo FODMAP', 'Fase de teste curta, com reintrodução', 'Intestino', 'Combinação alternativa usando alimentos frequentemente disponíveis em porções baixas em FODMAP. Quantidade e marcas importam.', 'Confirme porções no app/guia Monash com nutricionista. A fase estrita é curta; faça reintrodução e personalize para evitar restrição prolongada.', '[{"label":"Monash — lista de alimentos FODMAP","url":"https://monashfodmap.com/about-fodmap-and-ibs/high-and-low-fodmap-foods/"},{"label":"Monash — etapas da dieta","url":"https://www.monashfodmap.com/blog/3-phases-low-fodmap-diet/"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Ovos mexidos com bolacha de arroz simples e kiwi em porção baixa em FODMAP."},{"time":"10:00","name":"Lanche","items":"Tangerina ou laranja, porção conferida no guia Monash."},{"time":"12:30","name":"Almoço","items":"Batata, peixe sem molho pronto e cenoura/pepino; confira as porções."},{"time":"16:00","name":"Lanche","items":"Leite ou iogurte sem lactose, conforme tolerância."},{"time":"19:00","name":"Jantar","items":"Arroz, ovos ou frango simples e vagem. Evite alho/cebola durante a fase de teste conforme orientação."}]'::jsonb, 'sii-fodmap', 2, 'Cardápio B', true),
('plano-sii-fodmap-c', 'Intestino irritável: exemplo baixo FODMAP', 'Fase de teste curta, com reintrodução', 'Intestino', 'Terceira combinação demonstrativa. A classificação depende da porção; a tolerância individual também varia.', 'Use apenas com diagnóstico e orientação. Se não houver melhora após a fase de teste, converse com o profissional sobre outras estratégias.', '[{"label":"Monash — lista de alimentos FODMAP","url":"https://monashfodmap.com/about-fodmap-and-ibs/high-and-low-fodmap-foods/"},{"label":"Monash — etapas da dieta","url":"https://www.monashfodmap.com/blog/3-phases-low-fodmap-diet/"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Aveia certificada em porção baixa em FODMAP preparada com leite sem lactose; mirtilos em porção conferida."},{"time":"10:00","name":"Lanche","items":"Kiwi ou tangerina em porção baixa em FODMAP."},{"time":"12:30","name":"Almoço","items":"Arroz, ovos, cenoura e pepino; temperos simples sem alho/cebola."},{"time":"16:00","name":"Lanche","items":"Bolacha de arroz simples com queijo maturado se tolerado."},{"time":"19:00","name":"Jantar","items":"Batata, frango sem marinada e abobrinha; valide as porções no guia Monash."}]'::jsonb, 'sii-fodmap', 3, 'Cardápio C', true),
('plano-lactose-b', 'Intolerância à lactose: exemplo sem lactose', 'Manter cálcio e vitamina D', 'Intestino', 'Variação com bebida de soja fortificada e fontes alimentares de cálcio. Nem todo mundo precisa excluir completamente a lactose.', 'Confira rótulos de bebidas vegetais fortificadas e mantenha ingestão adequada de cálcio e vitamina D com apoio profissional.', '[{"label":"NIDDK — alimentação para intolerância à lactose","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/lactose-intolerance/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Cereal/aveia com bebida de soja fortificada com cálcio e banana."},{"time":"10:00","name":"Lanche","items":"Laranja ou mamão, conforme tolerância."},{"time":"12:30","name":"Almoço","items":"Arroz, sardinha com espinhas macias se apropriado, legumes e feijão se tolerado."},{"time":"16:00","name":"Lanche","items":"Tapioca com ovo ou iogurte sem lactose."},{"time":"19:00","name":"Jantar","items":"Mandioca, frango e brócolis cozido se tolerado."}]'::jsonb, 'lactose', 2, 'Cardápio B', true),
('plano-lactose-c', 'Intolerância à lactose: exemplo sem lactose', 'Manter cálcio e vitamina D', 'Intestino', 'Combinação alternativa sem leite comum, com escolhas sem lactose e alimentos que podem compor uma dieta variada.', 'A tolerância é individual. Iogurte sem lactose e bebidas vegetais fortificadas são opções; não confunda intolerância com alergia ao leite.', '[{"label":"NIDDK — alimentação para intolerância à lactose","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/lactose-intolerance/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Tapioca com ovo e bebida de soja fortificada, se tolerada."},{"time":"10:00","name":"Lanche","items":"Banana com castanhas, se toleradas."},{"time":"12:30","name":"Almoço","items":"Arroz, frango, couve e cenoura cozidas."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose com aveia, se ambos forem tolerados."},{"time":"19:00","name":"Jantar","items":"Batata, peixe e brócolis ou outra verdura tolerada."}]'::jsonb, 'lactose', 3, 'Cardápio C', true),
('plano-celiaca-b', 'Doença celíaca: exemplo sem glúten', 'Somente após confirmação diagnóstica', 'Intestino', 'Segunda combinação com alimentos naturalmente sem glúten. A segurança depende também do preparo e da ausência de contaminação cruzada.', 'Não retire o glúten antes dos exames se ainda não recebeu diagnóstico. Após diagnóstico, use ingredientes e utensílios seguros e separados.', '[{"label":"NIDDK — dieta para doença celíaca","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/eating-diet-nutrition"},{"label":"NIDDK — diagnóstico de doença celíaca","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/diagnosis"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Cuscuz de milho sem contaminação com ovo e mamão."},{"time":"10:00","name":"Lanche","items":"Laranja ou banana."},{"time":"12:30","name":"Almoço","items":"Mandioca, carne/frango e legumes preparados em superfície limpa e separada."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose conforme tolerância e castanhas embaladas sem contaminação."},{"time":"19:00","name":"Jantar","items":"Arroz, peixe e abobrinha; confira caldos, temperos, molhos e rótulos."}]'::jsonb, 'celiaca', 2, 'Cardápio B', true),
('plano-celiaca-c', 'Doença celíaca: exemplo sem glúten', 'Somente após confirmação diagnóstica', 'Intestino', 'Terceira combinação usando raízes, arroz, ovos e proteínas sem empanamento. Verifique todos os ingredientes processados.', 'Para doença celíaca confirmada, a dieta sem glúten é estrita. Evite contato de utensílios, torradeira, tábuas e superfícies com alimentos com glúten.', '[{"label":"NIDDK — dieta para doença celíaca","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/eating-diet-nutrition"}]'::jsonb, null, 'Conforme sede e orientação profissional', '[{"time":"07:30","name":"Café da manhã","items":"Pão certificado sem glúten com ovo e uma fruta."},{"time":"10:00","name":"Lanche","items":"Mamão ou banana."},{"time":"12:30","name":"Almoço","items":"Arroz, feijão e peixe grelhado com cenoura; preparo em área segura."},{"time":"16:00","name":"Lanche","items":"Tapioca com queijo sem lactose, se tolerado."},{"time":"19:00","name":"Jantar","items":"Purê de batata, frango e verduras; confira rótulos de temperos e produtos."}]'::jsonb, 'celiaca', 3, 'Cardápio C', true)
on conflict (id) do update set
  name = excluded.name,
  goal = excluded.goal,
  category = excluded.category,
  summary = excluded.summary,
  caution = excluded.caution,
  sources = excluded.sources,
  kcal = null,
  water = excluded.water,
  meals = excluded.meals,
  condition_key = excluded.condition_key,
  variant = excluded.variant,
  variant_label = excluded.variant_label,
  is_active = true,
  updated_at = now();
