alter table public.diet_plans
  add column if not exists category text not null default 'Digestivo',
  add column if not exists summary text not null default '',
  add column if not exists caution text not null default '',
  add column if not exists sources jsonb not null default '[]'::jsonb;

alter table public.diet_plans alter column kcal drop not null;
update public.diet_plans set is_active = false where id in ('di1', 'di2', 'di3');

insert into public.diet_plans (id, name, goal, category, summary, caution, sources, kcal, water, meals, is_active)
values
('plano-gastrite', 'Gastrite: refeições de exemplo', 'Sintomas variam; escolha o que tolera', 'Estômago',
 'Um dia de refeições simples para testar tolerância. Não existe uma lista universal que cure gastrite; alimentação não elimina H. pylori nem substitui tratar a causa.',
 'Evite álcool, especialmente com gastropatia erosiva, e converse com o médico sobre a causa. Não suspenda anti-inflamatórios prescritos sem orientação. Troque qualquer item que piore seus sintomas.',
 '[{"label":"NIDDK — dieta na gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"},{"label":"NIDDK — tratamento da gastrite","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/treatment"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Mingau de aveia com banana madura; água. Se aveia incomodar, troque por tapioca simples com ovo."},{"time":"10:00","name":"Lanche","items":"Mamão ou banana, conforme tolerância."},{"time":"12:30","name":"Almoço","items":"Arroz, frango preparado sem fritura, cenoura e abobrinha cozidas."},{"time":"16:00","name":"Lanche","items":"Tapioca pequena com ovo ou fruta tolerada."},{"time":"19:00","name":"Jantar","items":"Batata cozida ou purê simples, peixe assado e abóbora cozida."}]'::jsonb, true),
('plano-gastrite-autoimune', 'Gastrite autoimune: refeições equilibradas', 'Manter nutrição e acompanhar ferro/B12', 'Estômago',
 'Exemplo de alimentação variada. Gastrite autoimune pode prejudicar a absorção de ferro e vitamina B12; o plano alimentar sozinho pode não corrigir deficiências.',
 'Peça à equipe clínica acompanhamento de hemograma, ferro e vitamina B12. Suplementação ou injeções dependem de avaliação e exames; não se automedique.',
 '[{"label":"NIDDK — dieta na gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Ovo mexido, tapioca ou pão que você tolere e mamão."},{"time":"10:00","name":"Lanche","items":"Banana ou outra fruta tolerada."},{"time":"12:30","name":"Almoço","items":"Arroz, carne magra ou peixe, feijão se tolerado e legumes cozidos."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose se tolerado ou ovo cozido com uma fruta."},{"time":"19:00","name":"Jantar","items":"Arroz ou batata, frango ou peixe e folhas/legumes cozidos que não agravem sintomas."}]'::jsonb, true),
('plano-gastropatia-erosiva', 'Gastropatia reativa/erosiva: refeições de exemplo', 'Evitar álcool e avaliar a causa', 'Estômago',
 'O exemplo organiza refeições toleráveis; não cicatriza erosões. A causa pode envolver álcool, anti-inflamatórios ou refluxo biliar e precisa de avaliação clínica.',
 'Evite álcool e procure orientação antes de mudar qualquer medicamento. Sangue no vômito, fezes negras, fraqueza ou dor intensa requerem atendimento urgente.',
 '[{"label":"NIDDK — dieta na gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/eating-diet-nutrition"},{"label":"NIDDK — causas de gastrite e gastropatia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/symptoms-causes"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Tapioca com ovo e mamão, se tolerados; água."},{"time":"10:00","name":"Lanche","items":"Banana madura ou bolacha simples que você tolere."},{"time":"12:30","name":"Almoço","items":"Arroz, frango cozido/assado e cenoura ou abóbora cozida."},{"time":"16:00","name":"Lanche","items":"Fruta não ácida tolerada ou iogurte sem lactose, se tolerado."},{"time":"19:00","name":"Jantar","items":"Batata cozida, peixe assado e abobrinha cozida."}]'::jsonb, true),
('plano-dispepsia', 'Dispepsia: refeições menores de exemplo', 'Observar gatilhos pessoais', 'Estômago',
 'Para quem sente empachamento, este exemplo divide o dia em refeições menores. Café, gordura, bebidas gaseificadas e outros itens incomodam algumas pessoas, mas não todas.',
 'Não corte grupos alimentares de forma ampla. Ajuste um item por vez e procure médico/nutricionista se os sintomas persistirem, houver vômitos frequentes, dificuldade para engolir ou perda de peso.',
 '[{"label":"NIDDK — alimentação para dispepsia","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/indigestion-dyspepsia/eating-diet-nutrition"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Porção pequena de mingau de aveia se tolerado; alternativa: tapioca com ovo."},{"time":"10:00","name":"Lanche","items":"Banana ou mamão em pequena porção."},{"time":"12:30","name":"Almoço","items":"Porção confortável de arroz, frango e cenoura cozida; coma devagar."},{"time":"15:30","name":"Lanche","items":"Torrada simples ou fruta que não provoque sintomas."},{"time":"18:30","name":"Jantar","items":"Porção menor de batata, peixe e legumes cozidos; observe a saciedade."}]'::jsonb, true),
('plano-refluxo', 'Refluxo: refeições de exemplo', 'Jantar pelo menos 3 h antes de deitar', 'Estômago',
 'Exemplo com jantar cedo. Os gatilhos variam; reduza apenas os alimentos que você percebe piorarem o refluxo.',
 'Se houver sintomas à noite, tente encerrar a refeição pelo menos 3 horas antes de se deitar. Dificuldade para engolir, vômitos persistentes, sangue ou perda de peso precisam de avaliação.',
 '[{"label":"NIDDK — alimentação para refluxo","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Aveia com banana e água; ovo se desejar e tolerar."},{"time":"10:00","name":"Lanche","items":"Mamão ou melão, se tolerados."},{"time":"12:30","name":"Almoço","items":"Arroz, frango ou peixe e legumes cozidos."},{"time":"15:30","name":"Lanche","items":"Banana ou iogurte sem lactose, se tolerado."},{"time":"18:00","name":"Jantar","items":"Batata ou arroz, peixe/frango e abobrinha ou cenoura cozida. Ajuste o horário para ficar 3 h antes de deitar."}]'::jsonb, true),
('plano-sii-fodmap', 'Intestino irritável: exemplo baixo FODMAP', 'Fase de teste curta, com reintrodução', 'Intestino',
 'Um dia demonstrativo com trocas frequentemente usadas na fase baixa em FODMAPs. Porções e limites variam por alimento; confirme quantidades com nutricionista e fonte especializada.',
 'A fase estrita costuma ser curta (2–6 semanas) e deve ser acompanhada por nutricionista, seguida de reintrodução e personalização. Não é dieta para a vida toda nem tratamento para todo problema intestinal.',
 '[{"label":"Monash University — lista de alimentos FODMAP","url":"https://monashfodmap.com/about-fodmap-and-ibs/high-and-low-fodmap-foods/"},{"label":"Monash University — 3 etapas da dieta","url":"https://www.monashfodmap.com/blog/3-phases-low-fodmap-diet/"},{"label":"NIDDK — alimentação para intestino irritável","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/irritable-bowel-syndrome/eating-diet-nutrition"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Aveia em porção baixa em FODMAP conforme guia especializado, leite sem lactose e kiwi."},{"time":"10:00","name":"Lanche","items":"Laranja ou morangos em porção validada no guia FODMAP."},{"time":"12:30","name":"Almoço","items":"Arroz, frango sem marinada com alho/cebola, cenoura e abobrinha."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose ou bolacha de arroz simples."},{"time":"19:00","name":"Jantar","items":"Batata, peixe simples e vagem ou cenoura. Confira porções e ingredientes no guia da Monash."}]'::jsonb, true),
('plano-lactose', 'Intolerância à lactose: exemplo sem lactose', 'Manter cálcio e vitamina D', 'Intestino',
 'A lactose pode ser reduzida com versões sem lactose. Algumas pessoas toleram pequenas quantidades, iogurte ou queijos maturados; não é sempre necessário excluir todos os laticínios.',
 'Escolha versões sem lactose ou alternativas fortificadas e converse com nutricionista sobre cálcio e vitamina D. Intolerância não é alergia à proteína do leite.',
 '[{"label":"NIDDK — alimentação para intolerância à lactose","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/lactose-intolerance/eating-diet-nutrition"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Aveia preparada com leite sem lactose e banana."},{"time":"10:00","name":"Lanche","items":"Mamão ou laranja, conforme tolerância individual."},{"time":"12:30","name":"Almoço","items":"Arroz, feijão se tolerado, frango ou peixe e legumes."},{"time":"16:00","name":"Lanche","items":"Iogurte sem lactose ou queijo maturado se tolerado, com fruta."},{"time":"19:00","name":"Jantar","items":"Batata ou arroz, omelete e legumes cozidos."}]'::jsonb, true),
('plano-celiaca', 'Doença celíaca: exemplo sem glúten', 'Somente após confirmação diagnóstica', 'Intestino',
 'Exemplo baseado em alimentos naturalmente sem glúten. Na doença celíaca confirmada, a exclusão de trigo, cevada e centeio é estrita e contínua, inclusive para evitar contaminação cruzada.',
 'Se ainda está investigando doença celíaca, não retire o glúten antes de conversar com o médico: isso pode alterar os exames. Use produtos certificados/rotulados sem glúten e utensílios separados.',
 '[{"label":"NIDDK — dieta para doença celíaca","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/eating-diet-nutrition"},{"label":"NIDDK — exames para doença celíaca","url":"https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/diagnosis"}]'::jsonb,
 null, 'Hidratação conforme sede e orientação profissional',
 '[{"time":"07:30","name":"Café da manhã","items":"Tapioca com ovo e fruta. Se usar aveia, escolha produto certificado sem glúten."},{"time":"10:00","name":"Lanche","items":"Banana ou iogurte natural/sem lactose conforme tolerância."},{"time":"12:30","name":"Almoço","items":"Arroz, feijão, carne ou frango e legumes; confirme temperos, rótulos e preparo sem contato com glúten."},{"time":"16:00","name":"Lanche","items":"Fruta e castanhas sem contaminação cruzada, se toleradas."},{"time":"19:00","name":"Jantar","items":"Batata ou arroz, peixe e vegetais; usar utensílios e superfícies limpos e separados."}]'::jsonb, true)
on conflict (id) do update set
  name = excluded.name,
  goal = excluded.goal,
  category = excluded.category,
  summary = excluded.summary,
  caution = excluded.caution,
  sources = excluded.sources,
  kcal = null,
  water = excluded.water,
  meals = excluded.meals,
  is_active = true,
  updated_at = now();
