create table if not exists public.sports_supplements (
  id text primary key,
  name text not null,
  category text not null,
  purpose text not null,
  evidence text not null,
  use_case text not null,
  common_dose text not null,
  timing text not null,
  cautions text not null,
  sources jsonb not null default '[]'::jsonb check (jsonb_typeof(sources) = 'array'),
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.sports_goal_plans (
  id text primary key,
  goal_key text not null,
  name text not null,
  summary text not null,
  priorities jsonb not null default '[]'::jsonb check (jsonb_typeof(priorities) = 'array'),
  foods jsonb not null default '[]'::jsonb check (jsonb_typeof(foods) = 'array'),
  meals jsonb not null default '[]'::jsonb check (jsonb_typeof(meals) = 'array'),
  note text not null,
  sources jsonb not null default '[]'::jsonb check (jsonb_typeof(sources) = 'array'),
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.sports_supplements enable row level security;
alter table public.sports_goal_plans enable row level security;
grant select on public.sports_supplements, public.sports_goal_plans to anon, authenticated;
drop policy if exists "Sports supplement library is public" on public.sports_supplements;
create policy "Sports supplement library is public" on public.sports_supplements for select to anon, authenticated using (is_active);
drop policy if exists "Sports goal plans are public" on public.sports_goal_plans;
create policy "Sports goal plans are public" on public.sports_goal_plans for select to anon, authenticated using (is_active);

insert into public.sports_supplements (id,name,category,purpose,evidence,use_case,common_dose,timing,cautions,sources) values
('creatina-monohidratada','Creatina monohidratada','Força e potência','Aumenta os estoques musculares de fosfocreatina e pode ajudar em esforços repetidos de alta intensidade e nos ganhos de massa magra quando combinada ao treino.','Boa evidência para força, capacidade de exercício intenso e massa magra com treino resistido. Pode elevar o peso por água dentro do músculo, especialmente no início.','Uma opção simples para adultos saudáveis que fazem treino de força ou esforços intensos e repetidos.','Referência comum: 3–5 g por dia. Fase de saturação é opcional e não necessária para começar.','Todos os dias, no horário mais conveniente; consistência importa mais que pré ou pós-treino.','Doença renal, gravidez/amamentação, menores de 18 anos, uso de medicamentos ou histórico clínico: avaliar com médico/nutricionista. Informe o uso antes de exames, pois pode alterar creatinina sem significar lesão renal.','[{"label":"ISSN — posição sobre creatina","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5469049/"},{"label":"NIH ODS — suplementos para exercício","url":"https://ods.od.nih.gov/factsheets/ExerciseandAthleticPerformance-Consumer/"}]'::jsonb),
('whey-protein','Whey protein','Proteína alimentar em pó','Proteína do soro do leite que fornece aminoácidos para completar a ingestão do dia; não é obrigatória se a meta já for atingida com alimentos.','Proteína adequada associada ao treino de resistência ajuda adaptações musculares. O suplemento é conveniência, não efeito especial independente da dieta.','Use somente se facilitar alcançar a quantidade diária planejada ou uma refeição proteica prática.','Ajustar pelo rótulo e pela lacuna do dia; porção que forneça cerca de 20–40 g de proteína é uma faixa prática comum, não uma dose obrigatória.','Quando for conveniente, inclusive perto do treino; total diário e distribuição das refeições são mais importantes.','Contém leite; alergia à proteína do leite requer evitar. Intolerância à lactose pode exigir versão isolada sem lactose ou alternativa vegetal. Some a proteína do whey à alimentação total.','[{"label":"ISSN — proteína e exercício","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/"},{"label":"NIH ODS — suplementos para exercício","url":"https://ods.od.nih.gov/factsheets/ExerciseandAthleticPerformance-Consumer/"}]'::jsonb),
('maca-peruana','Maca peruana','Fitoterápico / alimento tradicional','É comercializada para energia, libido e desempenho; não há dose estabelecida para hipertrofia, emagrecimento ou ganho de peso.','Evidência clínica para melhorar composição corporal ou hipertrofia é insuficiente e heterogênea; não é possível prometer benefício nem recomendar dose esportiva.','Não deve substituir treino, refeições ou tratamento; pode ser discutida individualmente com profissional.','Sem dose validada para esses objetivos. Produtos variam na concentração e composição.','Não há horário comprovado para ganho de massa ou controle do peso.','Segurança de longo prazo e interações são incertas. Evite uso sem avaliação durante gestação/amamentação, em condições hormonossensíveis ou com medicamentos.','[{"label":"Revisão sistemática sobre maca e desempenho físico","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC11723211/"}]'::jsonb),
('bcaa','BCAA (leucina, isoleucina e valina)','Aminoácidos','Fornece três aminoácidos de cadeia ramificada. Proteína completa de alimentos ou whey também fornece BCAA e os demais aminoácidos essenciais.','Com ingestão suficiente de proteína completa, não está claro que BCAA acrescente ganho muscular; pouca evidência de benefício de desempenho.','Em geral não é prioridade se a alimentação atinge a meta de proteína.','Não há dose necessária para hipertrofia estabelecida quando a dieta já fornece proteína suficiente.','Sem horário comprovadamente superior para quem consome proteína adequada.','Pode deslocar orçamento de alimentos/suplementos mais úteis; revisar rótulo, ingredientes e condições clínicas com profissional.','[{"label":"NIH ODS — BCAA","url":"https://ods.od.nih.gov/factsheets/ExerciseandAthleticPerformance-Consumer/"},{"label":"ISSN — proteína e exercício","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/"}]'::jsonb),
('multivitaminico','Multivitamínico/mineral','Vitaminas e minerais','Pode complementar nutrientes quando há ingestão insuficiente ou necessidade identificada; não fornece energia ou proteína e não substitui alimentos variados.','Formulações variam muito e não há evidência de que um multivitamínico genérico aumente hipertrofia ou emagreça pessoas sem deficiência.','Considerar em dieta restritiva, deficiência ou necessidade específica após avaliação profissional.','Não há dose universal; seguir indicação profissional e evitar somar produtos que ultrapassem limites seguros.','Conforme rótulo e orientação; horário depende dos componentes e da tolerância.','Ferro, vitamina A, D, E, K e outros nutrientes podem causar efeitos ou interações em excesso. Atenção especial a anticoagulantes, gestação e doenças crônicas.','[{"label":"NIH ODS — multivitamínicos/minerais","url":"https://ods.od.nih.gov/factsheets/MVMS-Consumer/"}]'::jsonb),
('vitaminas-individuais','Vitaminas individuais (ex.: D, B12, ferro)','Reposição direcionada','Corrigem insuficiência ou deficiência específica; cada nutriente tem indicação diferente e não funciona como suplemento genérico para massa ou emagrecimento.','Benefício depende de deficiência, risco nutricional e indicação clínica. Não há dose esportiva universal para vitamina D, B12, ferro ou outros micronutrientes.','Avaliar padrão alimentar, sintomas, condições clínicas e, quando indicado, exames com profissional de saúde.','Somente conforme necessidade individual e orientação profissional; não iniciar ferro ou megadoses por conta própria.','Depende do nutriente, interação com alimentos/medicamentos e orientação do profissional.','Excesso pode ser tóxico e alguns suplementos interagem com medicamentos. Ferro requer cuidado especial; vitamina D em altas doses pode causar hipercalcemia.','[{"label":"NIH ODS — vitaminas e suplementos","url":"https://ods.od.nih.gov/factsheets/list-all/"},{"label":"NIH ODS — multivitamínicos/minerais","url":"https://ods.od.nih.gov/factsheets/MVMS-Consumer/"}]'::jsonb)
on conflict (id) do update set name=excluded.name,category=excluded.category,purpose=excluded.purpose,evidence=excluded.evidence,use_case=excluded.use_case,common_dose=excluded.common_dose,timing=excluded.timing,cautions=excluded.cautions,sources=excluded.sources,is_active=true,updated_at=now();

insert into public.sports_goal_plans (id,goal_key,name,summary,priorities,foods,meals,note,sources) values
('hipertrofia','hipertrofia','Ganho de massa e hipertrofia','Plano educativo com refeições ao longo do dia, proteína distribuída e energia suficiente para apoiar treino progressivo. Ajuste porções à fome, rotina, peso e evolução.','["Treino resistido progressivo e recuperação adequada","Adultos que treinam: referência geral de proteína 1,4–2,0 g/kg/dia; distribua em refeições","Pequeno superávit energético pode ajudar; ajuste gradualmente pelo acompanhamento do peso e desempenho","Inclua carboidratos para sustentar o treino e frutas, legumes e fibras"]'::jsonb,'["Arroz, feijão, batata, mandioca, aveia e pão","Ovos, frango, peixe, carnes magras, leite/iogurte, tofu e feijões","Banana, mamão, laranja, frutas da estação, verduras e legumes","Azeite, abacate, amendoim e castanhas em porções compatíveis"]'::jsonb,'[{"time":"07:00","name":"Café da manhã","items":"Aveia com leite ou bebida de soja fortificada, banana e ovos; ajuste quantidades à sua necessidade."},{"time":"10:00","name":"Lanche","items":"Iogurte natural ou alternativa proteica e fruta; whey pode substituir essa fonte se for conveniente."},{"time":"13:00","name":"Almoço","items":"Arroz, feijão, frango/peixe/tofu, legumes e salada; aumente a porção de carboidrato se precisar de mais energia."},{"time":"16:30","name":"Pré-treino / lanche","items":"Pão com ovos ou queijo, e fruta. Planeje o horário conforme tolerância e treino."},{"time":"20:00","name":"Jantar / pós-treino","items":"Batata, arroz ou mandioca com carne magra/ovos/tofu e legumes; não é obrigatório comer imediatamente após treinar."}]'::jsonb,'Cardápio de exemplo, não prescrição individual. A pesagem pode oscilar por água, glicogênio e creatina; observe tendências semanais e medidas com profissional.','[{"label":"ISSN — proteína e exercício","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/"},{"label":"ISSN — dietas e composição corporal","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5470183/"}]'::jsonb),
('emagrecimento','emagrecimento','Redução de gordura corporal','Plano educativo focado em saciedade, alimentos minimamente processados e preservação de massa muscular. Emagrecimento requer estratégia individual sustentável, não um alimento ou suplemento específico.','["Déficit energético moderado e sustentável, definido conforme contexto individual","Fonte de proteína em cada refeição; treino de força ajuda preservar massa magra","Priorize verduras, legumes, frutas, feijões e grãos integrais","Acompanhe energia, sono, fome e tendência do peso, sem dietas extremas"]'::jsonb,'["Feijão, lentilha, grão-de-bico, arroz integral ou comum em porção planejada","Ovos, frango, peixe, carnes magras, tofu, iogurte natural","Verduras, legumes variados, frutas inteiras","Água; reduza bebidas açucaradas se forem frequentes"]'::jsonb,'[{"time":"07:00","name":"Café da manhã","items":"Ovos mexidos com pão integral e uma fruta; ou iogurte natural com aveia e fruta."},{"time":"10:30","name":"Lanche opcional","items":"Fruta inteira e iogurte ou uma porção pequena de castanhas, se houver fome."},{"time":"13:00","name":"Almoço","items":"Metade do prato com verduras/legumes, feijão, arroz em porção individualizada e frango, peixe, ovo ou tofu."},{"time":"16:30","name":"Lanche","items":"Iogurte natural com fruta ou sanduíche simples com atum/frango/ovo e salada."},{"time":"19:30","name":"Jantar","items":"Prato semelhante ao almoço ou sopa de legumes com feijão/lentilha e uma fonte de proteína; ajuste às necessidades."}]'::jsonb,'Não calcule calorias ou déficit sem dados completos e contexto clínico. Gestação, amamentação, adolescência, histórico de transtorno alimentar ou doença crônica requerem acompanhamento.','[{"label":"ISSN — dietas e composição corporal","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5470183/"},{"label":"ISSN — proteína e exercício","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/"}]'::jsonb),
('ganho-de-peso','ganho-de-peso','Aumento de peso saudável','Estrutura alimentar com maior densidade energética e lanches planejados. A meta de ganho e as porções dependem da causa do baixo peso, saúde, atividade e evolução.','["Investigue perda involuntária de peso com profissional de saúde","Some refeições ou lanches nutritivos gradualmente em vez de depender de ultraprocessados","Inclua proteína, carboidratos e gorduras insaturadas ao longo do dia","Treino resistido pode apoiar ganho de massa magra quando apropriado"]'::jsonb,'["Leite/iogurte ou bebida de soja fortificada; vitaminas com fruta e aveia","Arroz, feijão, massas, batata, mandioca, pães e aveia","Ovos, frango, peixe, carne, tofu, queijos e leguminosas","Azeite, pasta de amendoim, abacate e castanhas; acrescente em pequenas porções"]'::jsonb,'[{"time":"07:00","name":"Café da manhã","items":"Vitamina de leite ou bebida de soja com banana, aveia e pasta de amendoim; ovos com pão ao lado."},{"time":"10:00","name":"Lanche","items":"Iogurte integral com granola/aveia e fruta ou sanduíche de queijo e ovo."},{"time":"13:00","name":"Almoço","items":"Arroz, feijão, carne/frango/ovo/tofu, legumes com azeite e uma fruta."},{"time":"16:30","name":"Lanche","items":"Pão com pasta de amendoim ou queijo e fruta; whey somente se ajudar a cobrir proteína, não calorias por obrigação."},{"time":"20:00","name":"Jantar","items":"Macarrão ou mandioca com molho, frango/atum/feijão e legumes; ceia com leite/iogurte se necessário para completar o dia."}]'::jsonb,'Ganho rápido não significa ganho de músculo. Perda involuntária, falta de apetite ou sintomas gastrointestinais persistentes precisam de avaliação médica/nutricional.','[{"label":"ISSN — proteína e exercício","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/"},{"label":"NHS — ganho de peso saudável","url":"https://www.nhs.uk/live-well/healthy-weight/managing-your-weight/healthy-ways-to-gain-weight/"}]'::jsonb)
on conflict (id) do update set goal_key=excluded.goal_key,name=excluded.name,summary=excluded.summary,priorities=excluded.priorities,foods=excluded.foods,meals=excluded.meals,note=excluded.note,sources=excluded.sources,is_active=true,updated_at=now();
