// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvonjcrpwjaujkugogem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2b25qY3Jwd2phdWprdWdvZ2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA4OTU5MzksImV4cCI6MjEwNjQ3MTkzOX0.UNK5flEOTbtFtGTnNiz8TuVGWniC6vTcEprW7pLDSoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});